[package]
edition      = "2024"
name         = "my-esp-project"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "my-esp-project"
path = "./src/bin/main.rs"

[dependencies]
embassy-executor = "0.10.0"
embassy-time = "0.5.0"
esp-backtrace = { version = "0.19.0", features = ["panic-handler", "println", "esp32"] }
esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32"] }
esp-hal = { version = "~1.1.0", features = ["log-04", "unstable", "esp32"] }
esp-println = { version = "0.17.0", features = ["log-04"] }
esp-rtos = { version = "0.3.0", features = ["embassy", "log-04", "esp32"] }
#esp-backtrace = { path = "../esp-hal/esp-backtrace", features = [
#    "panic-handler",
#    "println",
#    "esp32"
#] }
#esp-bootloader-esp-idf = { path = "../esp-hal/esp-bootloader-esp-idf", features = ["esp32"] }
#esp-hal = { path = "../esp-hal/esp-hal", features = ["log-04", "unstable", "esp32"] }
#esp-rtos = { path = "../esp-hal/esp-rtos", features = ["embassy", "log-04", "esp32"] }
#esp-println = { path = "../esp-hal/esp-println", features = ["log-04"] }

critical-section = "1.2.0"
panic-halt = "1.0.0"
embassy-futures = "0.1.2"

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = "s"

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug         = 2     # prefer slower builds but better debugging experience
lto           = 'fat'
opt-level     = 's'
